GET http://localhost:3001/api/people

###
POST http://localhost:3001/api/people/ HTTP/1.1
content-type: application/json

{
    "name": "Mary Poppendieck",
    "number": "613-859-9685"
}

###
DELETE http://localhost:3001/api/people/ HTTP/1.1